[package]
name = "day2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "star1"
path = "src/star1.rs"

[[bin]]
name = "star2"
path = "src/star2.rs"


[dependencies]
